# Generated by Django 6.0 on 2026-01-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Shared meeting link', null=True),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='meeting_platform',
            field=models.CharField(blank=True, help_text='google_meet, zoom, teams', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
