# Generated by Django 6.0 on 2026-02-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exchangerequest_meeting_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='meeting_platform',
            field=models.CharField(blank=True, choices=[('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams')], help_text='Google Meet or Teams', max_length=50, null=True),
        ),
    ]
